# Generated by Django 4.0.3 on 2022-05-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.CharField(default='', max_length=500)),
                ('blog_type', models.CharField(default='', max_length=500)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
