# Generated by Django 4.0.3 on 2022-05-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_database_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_database',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogs_database',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
