# Generated by Django 4.0.3 on 2022-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_database_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='loogin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('phone', models.IntegerField()),
                ('Date_of_birth', models.DateField()),
            ],
        ),
    ]
