# Generated by Django 4.0.3 on 2022-05-28 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_blogs_database_id_blogs_database_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_database',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 6, 12, 50, 492796)),
        ),
    ]
