# Generated by Django 4.0.3 on 2022-05-28 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blogs_database_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_database',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 6, 15, 25, 65708)),
        ),
        migrations.AlterField(
            model_name='blogs_database',
            name='unique_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
