# Generated by Django 4.0.3 on 2022-05-28 09:25

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_blogs_database_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_database',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 9, 25, 16, 906929)),
        ),
        migrations.AlterField(
            model_name='blogs_database',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
