# Generated by Django 4.0.3 on 2022-05-29 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blogs_database_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_database',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 6, 53, 8, 358317)),
        ),
    ]
