# Generated by Django 4.0.3 on 2022-05-30 17:16

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_alter_blogs_database_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_about', tinymce.models.HTMLField()),
                ('Project_url', models.CharField(default='', max_length=500)),
                ('decription', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 5, 30, 17, 16, 19, 145651))),
            ],
        ),
        migrations.AlterField(
            model_name='blogcomments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 17, 16, 19, 142857)),
        ),
        migrations.AlterField(
            model_name='blogs_database',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 17, 16, 19, 141046)),
        ),
    ]
