# Generated by Django 4.0.3 on 2022-05-30 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_project_alter_blogcomments_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 17, 27, 20, 529012)),
        ),
        migrations.AlterField(
            model_name='blogs_database',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 17, 27, 20, 527238)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 17, 27, 20, 530018)),
        ),
    ]
