# Generated by Django 4.0.3 on 2022-05-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
