# Generated by Django 4.0.3 on 2022-05-29 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_project_date_time_alter_project_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='message',
            new_name='decription',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='short_about',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 7, 41, 25, 739166)),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1),
        ),
    ]
