# Generated by Django 4.0.3 on 2022-05-29 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_project_date_time_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 8, 24, 56, 413208)),
        ),
    ]
