# Generated by Django 4.0.3 on 2022-05-29 10:30

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_project_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 10, 30, 2, 192558)),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_about',
            field=tinymce.models.HTMLField(),
        ),
    ]
