# Generated by Django 4.0.3 on 2022-05-30 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_project_date_time_alter_project_short_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 15, 16, 12, 34179)),
        ),
    ]
