# Generated by Django 4.0.3 on 2022-05-30 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_project_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_url',
            new_name='short_aboutshort_about',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 17, 27, 20, 524131)),
        ),
    ]
